/* Generated By:JavaCC: Do not edit this line. ParserGramaticaConstants.java */
package parser;

public interface ParserGramaticaConstants {

  int EOF = 0;
  int _TOKEN = 6;
  int _START = 7;
  int _LEFT = 8;
  int _RIGHT = 9;
  int _PREC = 10;
  int _TYPE = 11;
  int _UNION = 12;
  int _NONASSOC = 13;
  int _NULO = 14;
  int SEPARADOR = 15;
  int LCURL = 16;
  int RCURL = 17;
  int VERT_BAR = 18;
  int COLON = 19;
  int LLAVE = 20;
  int _ACCION = 21;
  int _DEF_CODIGO = 22;
  int identificador = 23;
  int literal = 24;
  int digito = 25;
  int numero = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "<token of kind 5>",
    "\"%token\"",
    "\"%start\"",
    "\"%left\"",
    "\"%right\"",
    "\"%prec\"",
    "\"%type\"",
    "\"%union\"",
    "\"%nonassoc\"",
    "\"%nulo\"",
    "\"%%\"",
    "\"%{\"",
    "\"%}\"",
    "\"|\"",
    "\":\"",
    "\"{\"",
    "<_ACCION>",
    "<_DEF_CODIGO>",
    "<identificador>",
    "<literal>",
    "<digito>",
    "<numero>",
    "\"<\"",
    "\">\"",
    "\";\"",
  };

}
